Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -44,7 +44,16 @@ jobs:
         curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
         echo run Mend dependencies scan
         mend dep --update --scope "GitHub Repository//${GITHUB_REPOSITORY##*/}"  --reachability --fail-policy
-        echo Run Mend code scan
+
+        # Check the exit code and take action if it's 9
+        if [ $? -e 9 ]; then
+          echo "Dependencies scan found policy violation"
+          # Add error handling logic here
+          exit 1  # Terminate the pipeline process
+        fi
+
+# The process continues if no policy violation was detected
+echo "Pipeline process continues..."
 
 #    - name: Start server
 #      run: npm start
